language: java
jdk:
  - openjdk8

env:
  - IDEA_VERSION=CL-2018.3.4
  - IDEA_VERSION=PC-LATEST-EAP-SNAPSHOT

script: xvfb-run gradle check

after_success:
  - gradle jacocoTestReport coveralls

jobs:
  include:
    - if: type = pull_request
      env: IDEA_VERSION=IC-192.5728.98
      script: xvfb-run gradle check verifyPlugin
    - stage: deploy
      if: branch IN (Stable) AND type = push
      env: IDEA_VERSION=IC-192.5728.98 JI_CHANNELS=$TRAVIS_BRANCH
      script: xvfb-run gradle publishPlugin
